### ISSUE TITLE
Approve brigade-gitlab-gateway ownership change

### ISSUE THREAD

**Issue by lukepatrick** [lukepatrick/brigade-gitlab-gateway#6]
Hello All. Exciting news in the world of Brigade, it has recently been accepted to [CNCF as a Sandbox prohect](https://www.cncf.io/sandbox-projects/). Brigade core is moving to the CNCF organization which means CNCF becomes the owner of the code. 

I have been invited to move my Brigade-related projects into the new BrigadeCore organization, which would include transferring this repo to BrigadeCore and ownership to CNCF. As I have accepted Pull Requests from others, I am asking for their ok to change ownership of this repo. 

Please let me know if you have any concerns
@rawkode 
@vranystepan

**Comment by vranystepan** [comment]
fine by me :+1:

**Comment by rawkode** [comment]
Sounds great 👍
